#:kivy 1.8.0
<Controller>:
    GridLayout:
        rows:9
        cols:9
        padding: 2
        spacing: 2
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
        Label:
            text: "?"
            
